/**
 * lib/passport-data.ts
 * Static demo travel history per account for the Traveller Passport feature.
 */

export interface PassportStay {
  id: string;
  hotelName: string;
  city: string;
  country: string;
  flag: string;
  checkIn: string;
  checkOut: string;
  nights: number;
  rating: number;
  tripType: "Business" | "Family" | "Couple" | "Solo";
  reviewText: string;
  topics: string[];
  photoCount: number;
  pointsEarned: number;
}

export const PASSPORT_HISTORIES: Record<string, PassportStay[]> = {
  james: [
    {
      id: "j1",
      hotelName: "The Peninsula Tokyo",
      city: "Tokyo",
      country: "Japan",
      flag: "🇯🇵",
      checkIn: "Jan 12, 2026",
      checkOut: "Jan 15, 2026",
      nights: 3,
      rating: 5,
      tripType: "Business",
      reviewText: "Impeccable in every detail. The Peninsula's legendary service lives up to its reputation — the business lounge was exceptional and the location perfect for meetings in Marunouchi. Wifi was fast and reliable throughout.",
      topics: ["Staff & Service", "Location", "WiFi & Internet"],
      photoCount: 2,
      pointsEarned: 36,
    },
    {
      id: "j2",
      hotelName: "Marina Bay Sands",
      city: "Singapore",
      country: "Singapore",
      flag: "🇸🇬",
      checkIn: "Feb 3, 2026",
      checkOut: "Feb 6, 2026",
      nights: 3,
      rating: 5,
      tripType: "Business",
      reviewText: "The infinity pool is genuinely one of the most spectacular sights in hospitality. Conference facilities were world class. Room views over the Marina at night are something I won't forget.",
      topics: ["Pool & Fitness", "Room Comfort", "Location"],
      photoCount: 4,
      pointsEarned: 41,
    },
    {
      id: "j3",
      hotelName: "Hotel Adlon Kempinski",
      city: "Berlin",
      country: "Germany",
      flag: "🇩🇪",
      checkIn: "Feb 24, 2026",
      checkOut: "Feb 26, 2026",
      nights: 2,
      rating: 4,
      tripType: "Business",
      reviewText: "Historic grandeur meets modern efficiency. The breakfast buffet was outstanding and the Brandenburg Gate location is unbeatable. Check-in was slightly slow but staff made up for it with genuine warmth.",
      topics: ["Food & Breakfast", "Location", "Check-in & Check-out"],
      photoCount: 1,
      pointsEarned: 26,
    },
    {
      id: "j4",
      hotelName: "Four Seasons George V",
      city: "Paris",
      country: "France",
      flag: "🇫🇷",
      checkIn: "Mar 18, 2026",
      checkOut: "Mar 21, 2026",
      nights: 3,
      rating: 5,
      tripType: "Business",
      reviewText: "Set the bar for everything. The floral arrangements alone are worth the visit. Michelin-starred dining in-house, suites that feel like private apartments, and staff who remember your name by day two.",
      topics: ["Food & Breakfast", "Room Comfort", "Staff & Service", "Value"],
      photoCount: 3,
      pointsEarned: 46,
    },
    {
      id: "j5",
      hotelName: "Hotel Excelsior Vittoria",
      city: "Pompei",
      country: "Italy",
      flag: "🇮🇹",
      checkIn: "Apr 7, 2026",
      checkOut: "Apr 10, 2026",
      nights: 3,
      rating: 4,
      tripType: "Business",
      reviewText: "A hidden gem perched above the Bay of Naples. Terrace views are absolutely cinematic. The property feels steeped in history and the staff go out of their way to make every meal memorable.",
      topics: ["Location", "Food & Breakfast", "Staff & Service"],
      photoCount: 2,
      pointsEarned: 36,
    },
  ],

  sarah: [
    {
      id: "s1",
      hotelName: "Walt Disney World Swan Resort",
      city: "Orlando",
      country: "United States",
      flag: "🇺🇸",
      checkIn: "Jun 20, 2025",
      checkOut: "Jun 27, 2025",
      nights: 7,
      rating: 5,
      tripType: "Family",
      reviewText: "Perfect family base for Disney. The kids absolutely loved it — the pool area kept them busy every evening. Walking distance to EPCOT was a game changer with little ones. Breakfast spread was brilliant.",
      topics: ["Pool & Fitness", "Food & Breakfast", "Location"],
      photoCount: 8,
      pointsEarned: 71,
    },
    {
      id: "s2",
      hotelName: "Excellence Playa Mujeres",
      city: "Cancun",
      country: "Mexico",
      flag: "🇲🇽",
      checkIn: "Aug 10, 2025",
      checkOut: "Aug 17, 2025",
      nights: 7,
      rating: 5,
      tripType: "Family",
      reviewText: "All-inclusive done right. Every restaurant was excellent and the kids club genuinely entertained our children for hours each day. The beach was pristine and the swim-up bar was a nice adult bonus after bedtime.",
      topics: ["Food & Breakfast", "Pool & Fitness", "Cleanliness"],
      photoCount: 6,
      pointsEarned: 61,
    },
    {
      id: "s3",
      hotelName: "The Goring",
      city: "London",
      country: "United Kingdom",
      flag: "🇬🇧",
      checkIn: "Oct 15, 2025",
      checkOut: "Oct 19, 2025",
      nights: 4,
      rating: 4,
      tripType: "Family",
      reviewText: "Quintessentially British and wonderfully family-friendly. The garden suite had enough space for all of us. Afternoon tea was a real highlight for the kids. Location near Buckingham Palace made sightseeing effortless.",
      topics: ["Room Comfort", "Food & Breakfast", "Location"],
      photoCount: 5,
      pointsEarned: 56,
    },
    {
      id: "s4",
      hotelName: "Park Hyatt Sydney",
      city: "Sydney",
      country: "Australia",
      flag: "🇦🇺",
      checkIn: "Jan 3, 2026",
      checkOut: "Jan 10, 2026",
      nights: 7,
      rating: 5,
      tripType: "Family",
      reviewText: "Waking up to Opera House views every morning never got old. The pool on the upper deck with the harbour as a backdrop is spectacular. Staff were endlessly patient with our energetic kids.",
      topics: ["Location", "Pool & Fitness", "Staff & Service", "Room Comfort"],
      photoCount: 7,
      pointsEarned: 71,
    },
    {
      id: "s5",
      hotelName: "Westin Broomfield Denver",
      city: "Broomfield",
      country: "United States",
      flag: "🇺🇸",
      checkIn: "Apr 3, 2026",
      checkOut: "Apr 8, 2026",
      nights: 5,
      rating: 4,
      tripType: "Family",
      reviewText: "Great base for exploring the Rockies. The rooms were spacious enough for the whole family and the breakfast selection was solid. Kids loved the indoor pool. A reliable, comfortable stay.",
      topics: ["Room Comfort", "Pool & Fitness", "Food & Breakfast"],
      photoCount: 3,
      pointsEarned: 41,
    },
  ],

  alex: [
    {
      id: "a1",
      hotelName: "Pulitzer Amsterdam",
      city: "Amsterdam",
      country: "Netherlands",
      flag: "🇳🇱",
      checkIn: "Feb 14, 2026",
      checkOut: "Feb 18, 2026",
      nights: 4,
      rating: 4,
      tripType: "Solo",
      reviewText: "Staying in a row of beautifully restored canal houses was exactly the Amsterdam experience I wanted. The in-house bar was lively without being rowdy. Perfect solo base for cycling the Jordaan neighbourhood.",
      topics: ["Location", "Room Comfort", "Staff & Service"],
      photoCount: 3,
      pointsEarned: 41,
    },
    {
      id: "a2",
      hotelName: "Bairro Alto Hotel",
      city: "Lisbon",
      country: "Portugal",
      flag: "🇵🇹",
      checkIn: "Mar 5, 2026",
      checkOut: "Mar 10, 2026",
      nights: 5,
      rating: 5,
      tripType: "Solo",
      reviewText: "Boutique perfection in the heart of historic Lisbon. The rooftop bar alone is worth booking for. The staff had a warmth that made it feel like staying with friends. Incredible value for the quality offered.",
      topics: ["Location", "Staff & Service", "Value", "Food & Breakfast"],
      photoCount: 2,
      pointsEarned: 36,
    },
    {
      id: "a3",
      hotelName: "Capella Bangkok",
      city: "Bangkok",
      country: "Thailand",
      flag: "🇹🇭",
      checkIn: "Apr 4, 2026",
      checkOut: "Apr 11, 2026",
      nights: 7,
      rating: 5,
      tripType: "Solo",
      reviewText: "Riverside tranquility in one of the world's most chaotic cities. The contrast is part of the magic. Spa was extraordinary and the breakfast on the river terrace was an hour I looked forward to every morning.",
      topics: ["Spa & Wellness", "Food & Breakfast", "Location", "Room Comfort"],
      photoCount: 4,
      pointsEarned: 46,
    },
  ],

  emma: [
    {
      id: "e1",
      hotelName: "Hotel Danieli",
      city: "Venice",
      country: "Italy",
      flag: "🇮🇹",
      checkIn: "Sep 5, 2025",
      checkOut: "Sep 9, 2025",
      nights: 4,
      rating: 5,
      tripType: "Couple",
      reviewText: "Arriving by water taxi to this 14th century palazzo at golden hour is something no photograph can capture. The rooftop restaurant with Grand Canal views is the most romantic dinner setting we've ever experienced.",
      topics: ["Location", "Food & Breakfast", "Room Comfort", "Staff & Service"],
      photoCount: 6,
      pointsEarned: 61,
    },
    {
      id: "e2",
      hotelName: "Canaves Oia Epitome",
      city: "Santorini",
      country: "Greece",
      flag: "🇬🇷",
      checkIn: "Oct 1, 2025",
      checkOut: "Oct 6, 2025",
      nights: 5,
      rating: 5,
      tripType: "Couple",
      reviewText: "The caldera views from our infinity pool suite are something we still talk about daily. Every sunset felt like it was staged for us personally. The spa was superb and the staff anticipated our needs before we voiced them.",
      topics: ["Pool & Fitness", "Spa & Wellness", "Room Comfort", "Staff & Service"],
      photoCount: 9,
      pointsEarned: 76,
    },
    {
      id: "e3",
      hotelName: "Augustine Hotel",
      city: "Prague",
      country: "Czech Republic",
      flag: "🇨🇿",
      checkIn: "Nov 20, 2025",
      checkOut: "Nov 24, 2025",
      nights: 4,
      rating: 4,
      tripType: "Couple",
      reviewText: "A 13th century monastery turned five-star hotel — the history seeps through every stone. The Augustine Bar makes a legendary negroni. Mala Strana location puts you perfectly between the castle and the old town.",
      topics: ["Location", "Food & Breakfast", "Room Comfort"],
      photoCount: 4,
      pointsEarned: 51,
    },
    {
      id: "e4",
      hotelName: "Mulia Resort Bali",
      city: "Nusa Dua",
      country: "Indonesia",
      flag: "🇮🇩",
      checkIn: "Jan 28, 2026",
      checkOut: "Feb 4, 2026",
      nights: 7,
      rating: 5,
      tripType: "Couple",
      reviewText: "The largest private beach in Bali and a spa that redefined what relaxation means to us. The Balinese staff carry a genuine warmth that no training manual can manufacture. We barely left the resort and never felt the need to.",
      topics: ["Spa & Wellness", "Pool & Fitness", "Cleanliness", "Staff & Service"],
      photoCount: 8,
      pointsEarned: 71,
    },
    {
      id: "e5",
      hotelName: "Hassler Roma",
      city: "Rome",
      country: "Italy",
      flag: "🇮🇹",
      checkIn: "Apr 5, 2026",
      checkOut: "Apr 9, 2026",
      nights: 4,
      rating: 5,
      tripType: "Couple",
      reviewText: "Perched at the top of the Spanish Steps, the Hassler is Rome distilled. Immaogine terrace dinner overlooking the city was the highlight of our entire trip. Timeless, impeccable and worth every penny.",
      topics: ["Location", "Food & Breakfast", "Staff & Service", "Value"],
      photoCount: 5,
      pointsEarned: 56,
    },
  ],

  michael: [
    {
      id: "m1",
      hotelName: "Hotel Zephyr San Francisco",
      city: "San Francisco",
      country: "United States",
      flag: "🇺🇸",
      checkIn: "Mar 10, 2026",
      checkOut: "Mar 12, 2026",
      nights: 2,
      rating: 3,
      tripType: "Business",
      reviewText: "Decent location near Fisherman's Wharf. The nautical theme is charming but the rooms felt dated. WiFi was inconsistent during video calls which was frustrating for a business stay. Would try somewhere different next visit.",
      topics: ["WiFi & Internet", "Room Comfort", "Location"],
      photoCount: 0,
      pointsEarned: 11,
    },
    {
      id: "m2",
      hotelName: "Portola Hotel & Spa",
      city: "Monterey",
      country: "United States",
      flag: "🇺🇸",
      checkIn: "Apr 10, 2026",
      checkOut: "Apr 12, 2026",
      nights: 2,
      rating: 4,
      tripType: "Business",
      reviewText: "Solid business hotel in a beautiful coastal setting. The conference facilities were excellent and the harbour views made the long meetings more bearable. A step up from my last business trip — would return.",
      topics: ["Location", "Staff & Service", "Room Comfort"],
      photoCount: 1,
      pointsEarned: 21,
    },
  ],
};
